[package]
name = "acala-primitives"
version = "1.3.1"
authors = ["Acala Developers"]
edition = "2018"

[dependencies]
bstringify = "0.1.2"
serde = { version = "1.0.124", optional = true }
codec = { package = "parity-scale-codec", version = "2.2.0", default-features = false, features = ["max-encoded-len"] }
num_enum = { version = "0.5.1", default-features = false }
parity-util-mem = { version = "0.10.0", default-features = false, features = ["primitive-types"] }

sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }

frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false }

evm = { version = "0.30.0", default-features = false, features = ["with-codec"] }
ethereum = { version = "0.9.0", default-features = false, features = ["with-codec"] }
rlp = { version = "0.5", default-features = false }
sha3 = { version = "0.9.1", default-features = false }

chainbridge = { git = "https://github.com/AcalaNetwork/chainbridge-substrate", default-features = false }

[dev-dependencies]
serde_json = { version = "1.0.64" }
hex-literal = "0.3.1"
primitives-proc-macro = { path = "./proc-macro" }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"num_enum/std",
	"parity-util-mem/std",

	"sp-runtime/std",
	"sp-core/std",
	"sp-std/std",
	"sp-io/std",

	"frame-support/std",

	"evm/std",
	"evm/with-serde",
	"ethereum/std",
	"ethereum/with-serde",
	"rlp/std",
	"sha3/std",

	"chainbridge/std",
]
runtime-benchmarks = [
	"chainbridge/runtime-benchmarks",
]
