relaychain:
  image: parity/polkadot:v0.9.22
  chain: rococo-local
  runtimeGenesisConfig:
    hrmp:
      preopenHrmpChannels:
        - sender: 2000
          recipient: 3000
          maxCapacity: 8
          maxMessageSize: 512
        - sender: 3000
          recipient: 2000
          maxCapacity: 8
          maxMessageSize: 512
    configuration:
      config:
        validation_upgrade_cooldown: 10
        validation_upgrade_delay: 10
  env:
    RUST_LOG: parachain::candidate-backing=trace,parachain::candidate-selection=trace,parachain::pvf=trace,parachain::collator-protocol=trace,parachain::provisioner=trace
  flags:
    - --rpc-methods=unsafe
    - --wasm-execution=compiled
    - --execution=wasm
  nodes:
    - name: alice
    - name: bob
    - name: charlie
parachains:
  - image: acala/karura-node:5ef8fb8e
    chain:
      base: karura-dev
      collators:
        - alice
        - bob
        - charlie
      sudo: alice
    id: 2000
    parachain: true
    flags:
      - --rpc-methods=unsafe
      - --force-authoring
      - --wasm-execution=compiled
      - --execution=wasm
    relaychainFlags:
      - --wasm-execution=compiled
      - --execution=wasm
    env:
      RUST_LOG: sc_basic_authorship=trace,cumulus-consensus=trace,cumulus-collator=trace,collator_protocol=trace,collation_generation=trace,aura=debug
    volumePath: /acala/data
    nodes:
      - flags:
          - --alice
      - flags:
          - --bob
      - flags:
          - --charlie
  - image: bifrost/node:stable-asset-xcm
    chain:
      base: bifrost-local
      sudo: alice
    id: 3000
    parachain: true
    flags:
      - --rpc-methods=unsafe
      - --force-authoring
      - --wasm-execution=compiled
      - --execution=wasm
    relaychainFlags:
      - --wasm-execution=compiled
      - --execution=wasm
    env:
      RUST_LOG: sc_basic_authorship=trace,cumulus-consensus=trace,cumulus-collator=trace,collator_protocol=trace,collation_generation=trace,aura=debug
    volumePath: /data
    nodes:
      - flags:
          - --alice
      - flags:
          - --bob
      - flags:
          - --charlie
