name: Docker Image
on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to build docker image (optional). Helpful to build docker image for release branches that don't have image
        required: false
        type: string

jobs:
  clean-up-actions:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'release-')
    steps:
      - name: Cancel Previous Runs
        # Only cancel non-master branch runs
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

  build-image:
    name: "Build docker image ${{ matrix.network }}"
    runs-on: ubuntu-latest
    needs: setup-matrix
    strategy:
      matrix:
        network: [karura, acala]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/acalanetwork/${{ matrix.network }}-node
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=${{ github.ref_name }}
            type=ref,event=pr
            type=sha
      - name: Change Dockerfile to support multi-platform
        run: |
          sed -i 's/FROM /FROM --platform=$BUILDPLATFORM /g' scripts/Dockerfile
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_ARGS=build-${{ matrix.network }}-release
            GIT_COMMIT=${{ env.GITHUB_SHA }}
            PROFILE=release
          file: scripts/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
